"""test migrations

Revision ID: 1ebd7a5d61f3
Revises: ce342f1f3c8f
Create Date: 2025-06-02 14:24:41.857413

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1ebd7a5d61f3"
down_revision: str | None = "ce342f1f3c8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
