"""def field mtm

Revision ID: 6341b5d46d4a
Revises: e59c03328d39
Create Date: 2025-06-07 12:44:16.012418

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6341b5d46d4a"
down_revision: str | None = "e59c03328d39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
