"""Initial revision

Revision ID: ce342f1f3c8f
Revises: 9ba39ac17485
Create Date: 2025-06-02 14:22:42.764134

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ce342f1f3c8f"
down_revision: str | None = "9ba39ac17485"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
